config/routes.rb
Popup::Application.routes.draw do
  resources :maps

  get "users/new"

  resources :pops
  resources :users

  match '/updatecontent', to: 'maps#updatecontent'
  match '/newtext', to: 'maps#newtext'
  match '/fetch', to: 'maps#fetch'
  match '/maps/:id/getmapid', to: 'maps#getmapid'
  match '/maps/:id/getuserid', to: 'maps#getuserid'
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  
  match '/signin', to: 'sessions#new'
  
  match '/signout', to: 'sessions#destroy', via: :delete
  

  root :to => 'home#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :name
  
  def updateContent(name, content, mapid, userid)
    @pop=Pop.find(:all, :conditions => ["name=? and map_id=? and user_id=?", name, mapid, userid])[0]
    @pop.comment=content
    @pop.save

  end
  
  def getMapId(id)
    return id
  end
  
  def getUserId(id)
    return  id
  end
  
  def getContent(mapid, userid)
    count=0
    output=""
    #@pops=Pop.all
    @pops=Pop.find(:all, :conditions => ["map_id=? and user_id=?", mapid, userid])
    output+="{"
    @pops.each do |pop|
      count+=1
      output+="\""+pop.name+"\":\""+pop.comment+"\""
      if (count<@pops.length)
        output+=","
      end

      @pops.length

    end
    output+="}"
    return output
  end
  
end

app/models/pop.rb
class Pop < ActiveRecord::Base
  attr_accessible :comment, :lat, :long, :name, :map_id, :user_id
  

  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :email, presence: true,
uniqueness: { case_sensitive: false }

  private
  #the method to create a unique token to be remembered for users to see his/her account without log in every time
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 
  include SessionsHelper
end
# love wen

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def fetch
    @map=Map.new

    render :json => @map.getContent([params[:mapid]][0],[params[:userid]][0])
  end

  def newtext
    @pop = Pop.new(name:[params[:name]][0], map_id:[params[:mapid]][0], user_id:[params[:userid]][0])
    @pop.save

  end

  def updatecontent
    @map=Map.new
    @map.updateContent([params[:name]][0], [params[:content]][0], [params[:mapid]][0],[params[:userid]][0])
  end

  def getmapid
    @map=Map.new

    render :json => @map.getMapId(params[:id])
  end

  def getuserid
    @map=Map.new

    render :json => @map.getUserId(current_user.id)
  end

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render json: @map, status: :created, location: @map }
      else
        format.html { render action: "new" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    @map = Map.find(params[:id])

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/pops_controller.rb
class PopsController < ApplicationController
  
  def fetch
    @pop=Pop.new
    
    render :json => @pop.getContent
  end
  
  def newtext
    @pop = Pop.new(name:[params[:name]][0])
    @pop.save
    
  end
  
  def updatecontent
    @pop=Pop.new
    @pop.updateContent([params[:name]][0], [params[:content]][0])
  end
  
  # GET /pops
  # GET /pops.json
  def index
    @pops = Pop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pops }
    end
  end

  # GET /pops/1
  # GET /pops/1.json
  def show
    @pop = Pop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pop }
    end
  end

  # GET /pops/new
  # GET /pops/new.json
  def new
    @pop = Pop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pop }
    end
  end

  # GET /pops/1/edit
  def edit
    @pop = Pop.find(params[:id])
  end

  # POST /pops
  # POST /pops.json
  def create
    @pop = Pop.new(params[:pop])

    respond_to do |format|
      if @pop.save
        format.html { redirect_to @pop, notice: 'Pop was successfully created.' }
        format.json { render json: @pop, status: :created, location: @pop }
      else
        format.html { render action: "new" }
        format.json { render json: @pop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pops/1
  # PUT /pops/1.json
  def update
    @pop = Pop.find(params[:id])

    respond_to do |format|
      if @pop.update_attributes(params[:pop])
        format.html { redirect_to @pop, notice: 'Pop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pops/1
  # DELETE /pops/1.json
  def destroy
    @pop = Pop.find(params[:id])
    @pop.destroy

    respond_to do |format|
      format.html { redirect_to pops_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #the method to show a specific user
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  #the method to create a new user
  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = "Welcome to the Netwoek Stickies App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  

  private

  #the method to sign in a user
  def signed_in_user
    redirect_to signin_path, notice: "Please sign in." unless signed_in?
  end

  #the method to check if the user is the authorized user to view a note
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pops_helper.rb
module PopsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "pop app", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Home", root_path %>
					</li>
					<% if signed_in? %>
					<li class="dropdown" id="accountmenu">

						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Maps<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<a tabindex="-1" href="/maps/1">Map 1</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/2">Map 2</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/3">Map 3</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/4">Map 4</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/5">Map 5</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/6">Map 6</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/7">Map 7</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/8">Map 8</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/9">Map 9</a>
							</li>
							<li>
								<a tabindex="-1" href="/maps/10">Map 10</a>
							</li>
						</ul>

					</li>
					<li>
						<%= link_to "My account", user_path(current_user) %>
					</li>
					<li>
						<%= link_to "Sign out", signout_path, method: "delete" %>
					</li>

					<% else %>

					<li>
						<%= link_to "Sign in", signin_path %>
					</li>
					<% end %>

				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Popup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

<%= yield %>

</body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/pops/_form.html.erb
<%= form_for(@pop) do |f| %>
  <% if @pop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pop.errors.count, "error") %> prohibited this pop from being saved:</h2>

      <ul>
      <% @pop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pops/edit.html.erb
<h1>Editing pop</h1>

<%= render 'form' %>

<%= link_to 'Show', @pop %> |
<%= link_to 'Back', pops_path %>

app/views/pops/index.html.erb
<h1>Listing pop ups</h1>

<table class="table">
  <tr>
  	<th>Map</th>
  	<th>User_name</th>
    <th>Lat_long</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pops.each do |pop| %>
  <tr>
  	<td><%= pop.map_id %></td>
  	<% @user=User.find(pop.user_id) %>
  	<td><%= @user.name %></td>
  	
    <td><%= pop.name %></td>
    <td><%= pop.comment %></td>
    <td><%= link_to 'Show', pop %></td>
    <td><%= link_to 'Edit', edit_pop_path(pop) %></td>
    <td><%= link_to 'Destroy', pop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pop', new_pop_path %>

app/views/pops/new.html.erb
<h1>New pop</h1>

<%= render 'form' %>

<%= link_to 'Back', pops_path %>

app/views/pops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lat:</b>
  <%= @pop.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @pop.long %>
</p>

<p>
  <b>Comment:</b>
  <%= @pop.comment %>
</p>


<%= link_to 'Edit', edit_pop_path(@pop) %> |
<%= link_to 'Back', pops_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(@user.errors.count, "error") %>.
	</div>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>
			* <%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %> <h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>